### ISSUE TITLE
Checklist for Feb 20th Deployment

### ISSUE THREAD

**Issue by naterush** [mito-ds/monorepo#64]
# Motivation
We are currently four big new changes that are WIP:
1. New packages. `mitosheet` goes to JLab 3.0.
2. State refactor. Removing unnecessary metadata.
3. Dependency flexibility. Allowing pandas to be more flexible (old versions). 
4. New graphing code. 

This is a lot of big things to test. We aim to get them all merged and deployed on test PyPi by the end of the week, so that we can explicitly test them _very thoroughly_, and then deploy. Below, we lay out what the timeline is for testing, and making sure that everything works.

# Overall Timeline

- [x] Merge in all open PRs by EOD Thursday. This includes state refactor, dependency flexibility, and new graphing code.
- [x] Go on Upwork and setup 3-5 (aiming for 5 usability tests) before the weekend. Give them instructions for installing the TestPyPi versions of Mito. You can see the job posting here: https://www.upwork.com/jobs/~015e9ac34042570db8
- [ ] Get the usability tests back before EOD Tuesday next week. 
- [ ] Aim for deployment by EOD Wednesday next week.

# Specific test cases

For a few of these changes, there are explicit test cases we want to run. I list them here:

## Test cases for the new packages
NOTE: run all these inside a virtual environment:

### Test the installer

**Command:**
```
python3 -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ mitoinstaller
python -m mitoinstaller install --test-pypi
```
**Check:**
1. The installer should work, and launch Mito (which should render and work)
2. Check you're on JLab 3.0, and the package installed is `mitosheet`

### Test upgrading with the installer

After the above test case, run the command:
```
python3 -m mitoinstaller upgrade --test-pypi
```
**Check:**
1. Mito still works, same packages are still installed.

Then, try the same with the command:
```
python3 -m mitoinstaller install --test-pypi
```
**Check:**
1. Mito still works, same packages are still installed.

### Direct mitosheet installation
```
python3 -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ mitosheet
```
**Check:**
1. You can launch jlab and render a mitosheet
2. Check you're on JLab 3.0, and the package installed is `mitosheet`

### Test installing mitosheet3 raw
```
python3 -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ mitosheet3
```
**Check:**
1. You can launch jlab and render a mitosheet
2. Check you're on JLab 3.0, and the package installed is `mitosheet3`

### Test upgrading mitosheet3

After the above test case, run the command:
```
python3 -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ mitosheet3 --upgrade
```
Everything should work as before.

### Test `mitosheet2` install works with correct commands

**Commands:**
```
python3 -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ mitosheet2
jupyter labextension install @jupyter-widgets/jupyterlab-manager@2
```
NOTE: on the `labextension` command, you might need to do `export NODE_OPTIONS=--openssl-legacy-provider` if it fails. This is a JupyterLab bug, not ours.

**Check:**
1. You can launch jlab and render a mitosheet
2. Check you're on JLab 2.0, and the package installed is `mitosheet2`

### Test existing `mitosheet2` users will not have a breaking upgrade process

**Commands:**
```
pip install mitosheet
jupyter labextension install @jupyter-widgets/jupyterlab-manager@2
pip uninstall mitosheet
python3 -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ mitosheet2 --upgrade
jupyter labextension install @jupyter-widgets/jupyterlab-manager@2
```
NOTE: on the `labextension` command, you might need to do `export NODE_OPTIONS=--openssl-legacy-provider` if it fails. This is a JupyterLab bug, not ours.

**Check:**
1. On launch JLab you get no errors (one popped up in the past)
2. You can render a mitosheet
2. Check you're on JLab 2.0, and the package installed is `mitosheet2`

### Test existing `mitosheet3` users will not have a breaking upgrade process
**Commands:**
```
python3 -m pip install mitosheet3
python3 -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ mitoinstaller
python3 -m mitoinstaller install --test-pypi
```

**Check:**
1. On launch JLab you get no errors (one popped up in the past)
2. You can render a mitosheet
2. Check you're on JLab 3.0, and the package installed is `mitosheet`

### Checklist for the new package tests

- [x] Nate ran these tests on Mac
- [x] Aaron ran these tests on Mac
- [ ] Someone ran these tests on Windows (TODO: figure out how to run these...)
- [ ] Communicated to relevant users, see doc in product on Notion call `Changes in Package Hierarchy Communication`
- [ ] Bumped versions correctly (medium version change) for mitosheet2

## Tests for dependency flexibility

We simply want to try to use Mito on a workflow with a bunch of different versions of Pandas. After we have a workflow selected (see below), I want to test on pandas versions: 0.24.2, 0.25.4, 1.0.0, and 1.4.5. 

Now, the main problem here is that I cannot personally install these earlier pandas versions. I'm thinking though... maybe we can use MyBinder instances? This will be annoying, as it's not a dev version, but I think we might have to. 

I'll think on this one, but I think 4 workflows on each of these would be great! I don't think we should do these with end users, b/c they very likely will just lead to installation errors.

## Tests for state refactor and new graphing code

These are best tested by a) doing workflows ourselves, and b) having users do workflows. @aarondr77 can we take one of the graphing workflows and adapt it (so it has a bit more transformations, or something), so we can send it out to users. Thoughts on what's best here?

EDIT: for now, I posted a UpWork job with the stack overflow analysis. I asked users to heavily user merge, pivot, and graphing, and we'll see what they end up doing here. They are also testing the new installer as well (they are installing locally).

**Comment by aarondr77** [comment]
I created a workflow that we can use for testing: https://www.notion.so/trymito/Extending-Quality-of-Life-Years-A-mission-from-Peter-Attia-417ae2d9066440ce934e26e0e4850dc8

**Comment by aarondr77** [comment]
The **test the installer** check is taking a really long time to run. I've been on this state of the installer for about 10 minutes. 

<img width="545" alt="Screen Shot 2022-02-21 at 11 33 38 AM" src="https://user-images.githubusercontent.com/18709905/154995216-db9ff7c8-8e8b-44ba-a6dc-2296126b92a0.png">

**Comment by naterush** [comment]
Ok, here's what I would like to do to figure this out:
1. Run the command `pip show mitoinstaller`. This will show the location of the installed package (it should be inside the venv, somewhere, prob site packages).
2. Open this file in code with `code /Users/nathanrush/monorepo/mitosheet/installer/venv/lib/python3.9/site-packages/mitoinstaller` 
3. Go to the `commands.py` file, on like 41, and delete the line that says `stdout=subprocess.PIPE`. This will make it so running the installer will print to the output, rather than save the output. I _think_ this shouldn't break any other things or cause other bugs, but we will see...
4. Run the test again, and post the output here, so we can see what is going on!

Note, every time you rerun the installer, you'll have to repeat these steps (b/c the install upgrades itself so freshest the Python files it has downloaded).

**Comment by aarondr77** [comment]
Yup. Seems like its an issue with test pypi. Its getting stuck `collecting mitosheet`. But I added the flag `--no-cache-dir` to the command.py file at line 105 and it seems to be working now!  

<img width="881" alt="Screen Shot 2022-02-21 at 1 39 29 PM" src="https://user-images.githubusercontent.com/18709905/155010973-5962cfc7-af1b-47c4-aaf6-6ccdfb0c9c0d.png">

**Comment by naterush** [comment]
@aarondr77 closing for now, but depending on install success we might want to add this. Other folks might be getting stuck with it.
